[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Add this to ensure Prisma Client is generated during build
[[plugins]]
  package = "netlify-plugin-prisma-client"

[functions]
  included_files = ["prisma/**"] 